# Generated by Django 5.2.3 on 2025-06-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vagas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vaga",
            name="tipo_vaga",
            field=models.CharField(
                choices=[
                    ("Presencial", "Presencial"),
                    ("Remoto", "Remoto"),
                    ("Híbrido", "Híbrido"),
                ],
                default=1,
                max_length=100,
            ),
            preserve_default=False,
        ),
    ]
