# Generated by Django 5.2.3 on 2025-06-18 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vagas", "0002_vaga_tipo_vaga"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vaga",
            name="publicada_em",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
