# Generated by Django 5.2.3 on 2025-06-17 16:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_empresa_remove_perfilcandidato_especialidades_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="empregadorperfil",
            name="cargo",
        ),
        migrations.AddField(
            model_name="candidatoperfil",
            name="cidade",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="candidatoperfil",
            name="criado_em",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="candidatoperfil",
            name="estado",
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name="empregadorperfil",
            name="cnpj",
            field=models.CharField(blank=True, max_length=18),
        ),
        migrations.AddField(
            model_name="empregadorperfil",
            name="criado_em",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="empregadorperfil",
            name="setor",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="empregadorperfil",
            name="empresa",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="empregadorperfil",
            name="usuario",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="perfil_empregador",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
