# Generated by Django 5.2.3 on 2025-06-18 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_candidatoperfil_telefone"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vaga",
            old_name="publicada_em",
            new_name="criada_em",
        ),
        migrations.RemoveField(
            model_name="vaga",
            name="empresa",
        ),
        migrations.RemoveField(
            model_name="vaga",
            name="salario",
        ),
        migrations.AddField(
            model_name="vaga",
            name="empregador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vagas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="vaga",
            name="tipo_contrato",
            field=models.CharField(
                choices=[("CLT", "CLT"), ("PJ", "PJ"), ("Freelancer", "Freelancer")],
                default="PJ",
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="vaga",
            name="localizacao",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="vaga",
            name="requisitos",
            field=models.TextField(blank=True),
        ),
    ]
