services:
  - type: web
    name: workmatch-api
    env: python
    buildCommand: ""
    startCommand: gunicorn workmatch_api.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: workmatch-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: workmatch_api.settings
