# Generated by Django 5.2.3 on 2025-06-18 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vagas", "0003_alter_vaga_publicada_em"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("curtida", "Curtida"), ("dispensada", "Dispensada")],
                        max_length=20,
                    ),
                ),
                ("criada_em", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "candidato",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vaga",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidaturas",
                        to="vagas.vaga",
                    ),
                ),
            ],
            options={
                "unique_together": {("candidato", "vaga")},
            },
        ),
    ]
